### PR TITLE
Bug #36 Add slash suffix if exists to complete path at http session

### LINKED ISSUE #36: [Bug]: Avoid trailing slash auto-remove in session
Adding trailing slash for path using http steps removes the slash when `session.URL()` is called when `Join` is used.

Generate client URL to send a request:
https://github.com/Telefonica/golium/blob/master/steps/http/session.go#L78

Sample of `path.Join` vs `url.Parse`:
* https://play.golang.org/p/5SKzKkyDeGd

Complete path with slash suffix if exists

### PR DESCRIPTION
**Pull request by ricardogarfe**
Don't remove trailing slash when `session.URL` function is executed to be able to tests API Rest paths defined as is
fixes #36 issue

### CODE REVIEW

File: steps/http/session.go [hunk 1]
```diff
@@ -74,11 +80,10 @@ func (s *Session) URL() (*url.URL, error) {
 	if err != nil {
 		return nil, fmt.Errorf("invalid endpoint URL '%s': %w", s.Request.Endpoint, err)
 	}
-	u, err = u.Parse(s.Request.Path)
-	if err != nil {
-		return nil, fmt.Errorf("invalid path URL '%s': %w", s.Request.Path, err)
+	u.Path = path.Join(u.Path, s.Request.Path)
```
Comment (mariolg) [inline steps/http/session.go:83]: Considering this guideline: https://hackernoon.com/never-forget-anything-before-after-and-while-coding-98d187ae4cf1 and the fact that is not intuitive that Join removes the last slash, I would suggest to add a note as a reminder for the whole change (maybe HACK or NOTE)

**Review by mariolg — APPROVED** [review]
LGTM

**Review by ismtabo — APPROVED** [review]
LGTM

**Review by cbrea — APPROVED** [review]
LGTM
